#%RAML 1.0 DataType

type: object
displayName: Order
properties: 
  exchanges: string[]
  action_type: string
  size_coin: number
  currency_to: string
  currency_in: string
  price?: number
  duration_sec?: number
  max_order_size?: number
  external_order_id?: string
  user_price?: number
  user_id?: string