#%RAML 1.0
---
title: Smart Trade
version: v0.3
protocols: [HTTP]
mediaType: application/json
baseUri: http://smart-trader/{version}/


/orderbook/{exchange}:
  description: Exchange name {exchange} or "Unified" for a unified orderbook
  /{currency_to}:
    description: Currency to buy / sell
    /{currency_from}:
      description: Currency that the orders are traded in
      get:

/reports:
  description: Smart-Trader reports APIs
  /sentOrders:
    post:
      description: Generat report on sent transactions data.
      body:
        application/json:
          properties:
            newConfig:
              description: Configuration object.
              required: true
              type: Config
  /profit:
    post:       